import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Google Contacts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon/logo.png" />
      </Head>
      <main>

      </main>
    </div>
  );
};

export default Home;
