import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Contacts from "../components/Contacts";
import HeaderOptions from "../components/HeaderOptions";

const Home: NextPage = () => {
  return (
    <div className=" flex flex-col flex-1">
      <Head>
        <title>Google Contacts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon/logo.png" />
      </Head>

      {/* main contact section */}
      <div className="mt-5">
        <HeaderOptions />
        <p className="text-gray-500 font-bold text-[10px] mx-11">CONTACTS (303)</p>
        <Contacts />
      </div>
    </div>
  );
};

export default Home;
