import { signIn } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";

const Login = () => {
  const handleLogin = async () => {
    await signIn("google");
  };
  return (
    <>
      <Head>
        <title>Google Contacts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon/logo.png" />
      </Head>
      <div className="grid h-screen w-screen  col-span-1 place-content-center">
        <Image
          src={"/icon/logo.png"}
          height={80}
          width={80}
          objectFit="cover"
        />
        <div className="mt-5">
          <button
            onClick={handleLogin}
            className="text-white bg-blue-700  py-3 px-6 rounded-md text-sm"
          >
            Login
          </button>
        </div>
      </div>
    </>
  );
};

export default Login;
